---
version: "3.4"
services:
  dolt:
    build:
      context: "../"
      dockerfile: "development/Dockerfile-dolt"
    depends_on:
      - "golden"
    command: /bin/sh -c /var/lib/dolt-on-start.sh
    env_file:
      - "dev.env"
      - "creds.env"
    volumes:
      - "../test_data/dolt_dbs:/var/lib/nautobot_dbs"
      - "../test_data/logs:/var/lib/logs"
      - "./dolt-config.yaml:/var/lib/dolt-config.yaml"
      - "./dolt-on-start.sh:/var/lib/dolt-on-start.sh"
    ports:
      - "3306:3306"
    healthcheck:
      test: dolt sql-client -u $$DOLT_USER -p $$DOLT_PASSWORD -q "show databases; select 'healthcheck';" --use-db $$DOLT_DB
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 50
  golden:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "mypassword"
      MYSQL_DATABASE: "nautobot"
      MYSQL_TCP_PORT: "3366"
    ports:
      - "3366:3366"
    volumes:
      # Unit tests require the createdb permission to clone the database
      - ./mysql-unittests.sql:/docker-entrypoint-initdb.d/mysql-unittests.sql
      - mysqldata_nautobot:/var/lib/mysql
  redis:
    image: "redis:6-alpine"
    command:
      - "sh"
      - "-c" # this is to evaluate the $REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    env_file:
      - "dev.env"
      - "creds.env"
    ports:
      - "6379:6379"
volumes:
  dolt_data: {}
  mysqldata_nautobot:
