FROM ubuntu:20.04

RUN apt update && apt install -y curl mariadb-client && \
    apt-get autoremove -y && \
    apt-get clean all && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/lib/nautobot

ARG DOLT_RELEASE="v0.41.4"
RUN curl -L https://github.com/dolthub/dolt/releases/download/${DOLT_RELEASE}/install.sh | bash

RUN dolt config --global --add user.name nautobot
RUN dolt config --global --add user.email opensource@networktocode.COM
RUN dolt config --global --add init.defaultbranch main

WORKDIR /var/lib/nautobot

COPY ./development/dolt-config.yaml /dolt-config.yaml

EXPOSE 3306

RUN dolt init --new-format

CMD DOLT_DEFAULT_BIN_FORMAT="__DOLT__" dolt sql-server --config /dolt-config.yaml
