---
version: "3.4"
services:
  redis:
    image: "redis:6-alpine"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    env_file:
      - "dev.env"
      - "creds_hosted.env"
    ports:
      - "6379:6379"
volumes:
  dolt_data: {}
