---
version: "3.8"

services:
  nautobot:
    environment:
      - "NAUTOBOT_DB_ENGINE=django.db.backends.mysql"
    env_file:
      - "development.env"
      - "creds.env"
  worker:
    environment:
      - "NAUTOBOT_DB_ENGINE=django.db.backends.mysql"
    env_file:
      - "development.env"
      - "creds.env"
  db:
    build:
      context: "../"
      dockerfile: "development/Dockerfile-dolt"
    command: /bin/sh -c "dolt --ignore-lock-file sql-server --config=/dolt-config.yaml"
    env_file:
      - "development.env"
      - "creds.env"
    volumes:
      - "dolt_data:/var/lib/nautobot"
      - "./dolt-config.yaml:/dolt-config.yaml"
    # set the port if you want to connect to the database directly with a client
    ports:
      - "3306:3306"
    healthcheck:
      test: dolt sql-client -u $$NAUTOBOT_DB_USER -p $$NAUTOBOT_DB_PASSWORD -q "show databases; select 'healthcheck';" --use-db $$NAUTOBOT_DB_NAME
      timeout: "10s"
      retries: 10

volumes:
  dolt_data: {}
